const namespace = 'DRAWER'

export const ON_DRAWER_OPEN_CHANGED = `${namespace}@ON_DRAWER_OPEN_CHANGED`
export const ON_DRAWER_MOBILE_OPEN_CHANGED = `${namespace}@ON_DRAWER_MOBILE_OPEN_CHANGED`
export const ON_DRAWER_USE_MINIFIED_CHANGED = `${namespace}@ON_DRAWER_USE_MINIFIED_CHANGED`
