// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'firebase.LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'firebase.REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'firebase.LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'firebase.FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'firebase.UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'firebase.CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'firebase.FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'firebase.LOGOUT_FIREBASE_USER';

export const INIT_AUTH = 'INIT_AUTH';

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
