export const SET_MINI_MODE = 'SET_MINI_MODE'
export const SET_MENU_OPEN = 'SET_MENU_OPEN'
export const SET_MOBILE_MENU_OPEN = 'SET_MOBILE_MENU_OPEN'
export const SET_MINI_SWITCH_VISIBILITY = 'SET_MINI_SWITCH_VISIBILITY' 
